#!/bin/bash

if [ "$1" = "upgrade" ]; then

	CONFIG=/boot/config.txt
	if grep -qw "osmcdev=rbp2" /proc/cmdline && [ -n "$2" ] && dpkg --compare-versions "$2" lt "3.0.500" && grep -qw "arm_freq=1000" $CONFIG && \
		grep -qw "core_freq=500" $CONFIG && grep -qw "sdram_freq=500" $CONFIG && grep -qw "over_voltage=2" $CONFIG
	then
		sed 's/^sdram_freq=500$/sdram_freq=450/g' -i $CONFIG
		echo "Updated Turbo overclock profile to sdram_freq=450"
		touch /tmp/reboot-needed
	fi
fi

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
	systemctl stop mediacenter.service >/dev/null 2>&1
	rm -rf /usr/share/kodi/addons/script.module.osmccommon
	rm -rf /usr/share/kodi/addons/script.module.osmcsetting.apfstore
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.logging
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.networking
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.pi
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.remotes
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.services
	rm -rf /usr/share/kodi/addons/script.module.osmc.osmcsetting.updates
	rm -rf /usr/share/kodi/addons/service.osmc.settings
	exit 0
fi
